export const USER_SESSION = 'USER_SESSION';
export const ALL_SUBJECTS = 'ALL_SUBJECTS';
export const CURRENT_SUBJECT = 'CURRENT_SUBJECT';
export const OVERALL_PROGRESS = 'OVERALL_PROGRESS';
export const RECENT_PERFORMANCE = 'RECENT_PERFORMANCE';
export const LEARNING_STREAK = 'LEARNING_STREAK';
export const CURRENT_TOPICS  = 'CURRENT_TOPICS';
export const CURRENT_TOPIC  = 'CURRENT_TOPIC';

export const CURRENT_SUB_TOPIC  = 'CURRENT_SUB_TOPIC';

export const WELCOME_MESSAGE    = 'WELCOME_MESSAGE';
export const LEARNING_PROGRESS  = 'LEARNING_PROGRESS';

export const RECOMMENDATION  = 'RECOMMENDATION';

// todo: add more action types